Repository brown-ccv/icesat2waves, pull requests merged in 2024-03, with the labels that each got.

#99 feat: isolate test suite
  .gitattributes
  .github/workflows/test_icesat2_tracks_pipeline.yml
  .github/workflows/test_test_suite.yml
  tests/test_steps.py
  tests/testdata/A02c_IOWAGA_thredds_prior-for-step-5.tar.gz
  tests/testdata/B01_SL_load_single_file-for-step-2.tar.gz
  tests/testdata/B02_make_spectra_gFT-for-step-3.tar.gz
  tests/testdata/B03_plot_spectra_ov-for-step-4.tar.gz
  tests/testdata/B04_angle-for-step-6.tar.gz
  tests/testdata/B05_define_angle-for-step-7.tar.gz
Labels: enhancement

#137 Rename IceSAT2_startup => config
  src/icesat2_tracks/analysis_db/A01b_ALT07_SHNH_variance_tester.py
  src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
  src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
  src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
  src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
  src/icesat2_tracks/analysis_db/B04_angle.py
  src/icesat2_tracks/analysis_db/B05_define_angle.py
  src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
  src/icesat2_tracks/config/config.py
Labels: :broom: Code cleanup

#143 Refactor test suite test_steps.py to run step that takes the longest first
  tests/test_steps.py
Labels: enhancement

#166 chore: delete .DS_Store file
  ._.DS_Store
Labels: :broom: Code cleanup

#164 chore: delete analyis_publish/ from root
  analyis_publish/PB01_regrid_filter.py
  analyis_publish/PB03_plot_reconstruction_vid.py
  analyis_publish/PB03_plot_spectra_3x3_ov.py
  analyis_publish/PB03_plot_spectra_case_v1.py
  analyis_publish/PB03_plot_spectra_case_v2.py
  analyis_publish/PB04_angle.py
  analyis_publish/PB04_angle_paper.py
  analyis_publish/PB04_angle_priors.py
  analyis_publish/PB05_define_angle.py
  analyis_publish/PB05_define_angle_supl.py
  analyis_publish/PB06_plot_reconstruction.py
  analyis_publish/PB06_plot_reconstruction_simple.py
  analyis_publish/PB07_plot_N_and_data.py
  analyis_publish/SB02_directional_distortion.py
  analyis_publish/SB05_2d_wavefield_emulator_puplish.py
Labels: :broom: Code cleanup

#159 chore: delete analysis_fake_data/ from root
  analysis_fake_data/A01_1D_spectra_and_ice.py
  analysis_fake_data/A01_1d_fake_surface_obs.py
  analysis_fake_data/S01_1D_fake_data_variance_conservation.py
  analysis_fake_data/wave_realizations.py
Labels: :broom: Code cleanup

#160 chore: delete config/ from root
  config/2021_IceSAT2_startup_local.py
  config/color_def.ai
  config/color_def.ase
  config/color_def.json
  config/color_def2.ase
  config/config_local.json
  config/generate_colors.py
Labels: :broom: Code cleanup

#162 chore: remove old env files
  environment.yml
  environment_small.yml
  py37_req_CCV.env
Labels: :broom: Code cleanup

#171 chore: delete SlideRule/ from root
  SlideRule/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  SlideRule/.ipynb_checkpoints/ocean_classification_slideRule-checkpoint.ipynb
  SlideRule/S01_SlideRule_compare.py
  SlideRule/S02_SlideRule_trials.py
  SlideRule/Untitled.ipynb
  SlideRule/environment.yml
  SlideRule/environment_py37.yml
  SlideRule/ocean_classification_slideRule.ipynb
  SlideRule/password.txt
Labels: :broom: Code cleanup

#123 Update Dockerfile
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  Dockerfile
Labels: enhancement

#132 Cleaning and formating files in the ICEsat2_SI_tools folder
  pyproject.toml
  src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
  src/icesat2_tracks/ICEsat2_SI_tools/beam_stats.py
  src/icesat2_tracks/ICEsat2_SI_tools/convert_GPS_time.py
  src/icesat2_tracks/ICEsat2_SI_tools/convert_julian.py
  src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
  src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
  src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
  src/icesat2_tracks/ICEsat2_SI_tools/lanczos.py
  src/icesat2_tracks/ICEsat2_SI_tools/read_ground_tracks.py
  src/icesat2_tracks/ICEsat2_SI_tools/sliderule_converter_tools.py
  src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
  src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
  src/icesat2_tracks/ICEsat2_SI_tools/wave_tools.py
  src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
  src/icesat2_tracks/analysis_db/B04_angle.py
Labels: :broom: Code cleanup

#189 chore: rename as per PEP 8
  README.md
  pyproject.toml
  src/icesat2waves/__init__.py
  src/icesat2waves/analysis_db/A02c_IOWAGA_thredds_prior.py
  src/icesat2waves/analysis_db/B01_SL_load_single_file.py
  src/icesat2waves/analysis_db/B02_make_spectra_gFT.py
  src/icesat2waves/analysis_db/B03_plot_spectra_ov.py
  src/icesat2waves/analysis_db/B04_angle.py
  src/icesat2waves/analysis_db/B05_define_angle.py
  src/icesat2waves/analysis_db/B06_correct_separate_var.py
  src/icesat2waves/analysis_db/__init__.py
  src/icesat2waves/app.py
  src/icesat2waves/clitools.py
  src/icesat2waves/config/__init__.py
  src/icesat2waves/config/color_def.ai
  src/icesat2waves/config/color_def.ase
  src/icesat2waves/config/color_def.json
  src/icesat2waves/config/config.json
  src/icesat2waves/config/generate_colors.py
  src/icesat2waves/config/startup.py
  src/icesat2waves/local_modules/__init__.py
  src/icesat2waves/local_modules/jonswap_gamma.py
  src/icesat2waves/local_modules/m_colormanager_ph3.py
  src/icesat2waves/local_modules/m_general_ph3.py
  src/icesat2waves/local_modules/m_spectrum_ph3.py
  src/icesat2waves/local_modules/m_tools_ph3.py
  src/icesat2waves/tools/__init__.py
  src/icesat2waves/tools/angle_optimizer.py
  src/icesat2waves/tools/beam_stats.py
  src/icesat2waves/tools/convert_GPS_time.py
  src/icesat2waves/tools/convert_julian.py
  src/icesat2waves/tools/filter_regrid.py
  src/icesat2waves/tools/generalized_FT.py
  src/icesat2waves/tools/iotools.py
  src/icesat2waves/tools/lanczos.py
  src/icesat2waves/tools/read_ground_tracks.py
  src/icesat2waves/tools/sliderule_converter_tools.py
  src/icesat2waves/tools/spectral_estimates.py
  src/icesat2waves/tools/spicke_remover.py
  src/icesat2waves/tools/wave_tools.py
  tests/test_steps.py
Labels: :broom: Code cleanup

#191 chore: update package name to icesat2waves
  .github/workflows/test_icesat2_tracks_pipeline.yml
  .github/workflows/test_test_suite.yml
  README.md
Labels: documentation, :broom: Code cleanup

#131 Clean files in local_modules
  src/icesat2waves/analysis_db/A02c_IOWAGA_thredds_prior.py
  src/icesat2waves/analysis_db/B01_SL_load_single_file.py
  src/icesat2waves/analysis_db/B02_make_spectra_gFT.py
  src/icesat2waves/analysis_db/B03_plot_spectra_ov.py
  src/icesat2waves/analysis_db/B04_angle.py
  src/icesat2waves/analysis_db/B05_define_angle.py
  src/icesat2waves/analysis_db/B06_correct_separate_var.py
  src/icesat2waves/local_modules/jonswap_gamma.py
  src/icesat2waves/local_modules/m_colormanager_ph3.py
  src/icesat2waves/local_modules/m_general_ph3.py
  src/icesat2waves/local_modules/m_spectrum_ph3.py
  src/icesat2waves/local_modules/m_tools_ph3.py
Labels: :broom: Code cleanup
